version: '3'

# --TODO--
# Vite + Svelte
# Browsersync

vars:
    GREETING: Hello, World!

tasks:
    default:
        deps: [task-once, task-watch]
        

    ### --- Run-Once Tasks --- ###
    task-once:
        deps: [go-air, tailwind]

    go-air:
        - air

    tailwind:
        - npx tailwindcss -i ./server/css/input.css -o ./server/css/output.css --watch


    ### --- Watch Tasks --- ###
    task-watch:
        - task watchable --watch --interval 2s

    watchable:
        deps: [templ-watch]

    templ-watch:
        cmds:
            - templ generate
        sources:
            - ./**/*.templ
